"""add item_order association table

Revision ID: 98211b3a8c74
Revises: 430af2c79d74
Create Date: 2024-07-10 22:40:12.085629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98211b3a8c74'
down_revision = '430af2c79d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_orders',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_orders')
    # ### end Alembic commands ###
